networks:
  backend:
    name: "${COMPOSE_PROJECT_NAME}"
services:
  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}.nginx"
    build:
      context: "../../docker/nginx"
      target: "local"
    image: "reverb-server/nginx"
    ports:
      - "${WEB_PORT:-80}:80"
    volumes:
      - "../../src:/var/www:cached"
    depends_on:
      - "php-fpm"
    networks:
      - "backend"
  php-fpm:
    container_name: "${COMPOSE_PROJECT_NAME}.php-fpm"
    build:
      context: "../../docker/php-fpm"
      target: "local"
    image: "reverb-server/php-fpm"
    volumes:
      - "../../src:/var/www:cached"
      - "./my-php.ini:/usr/local/etc/php/conf.d/my-php.ini"
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - "backend"
#  redis:
#    container_name: "${COMPOSE_PROJECT_NAME}.redis"
#    image: "redis:alpine"
#    ports:
#      - "${FORWARD_REDIS_PORT:-6379}:6379"
#    volumes:
#      - "redis:/data"
#    networks:
#      - "backend"
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      retries: 3
#      timeout: "5s"
volumes:
  redis:
